[package]
name = "rust-course"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "guess-game"
path = "src/guess-game/main.rs"

name = "programming-concept"
path = "src/programming-concepts/main.rs"

[dependencies]
rand = "0.8.5"